In [34]:
import pandas as pd
import numpy as np
import os 
import matplotlib.pyplot as plt
import pypsa
import yaml

### Scenario selection

In [35]:
PREFIX = "/mnt/c/Users/scl38887/Documents/git/pypsa-nz/"

In [36]:
OUTPUT = PREFIX + "results/figures/sensitivity/"

In [37]:
scenarios = {#"0": PREFIX + f"results/nz_2030_exp/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2030_0.071_AB_0export.nc",
            "0": PREFIX + f"results/nz_2035_lowfix_lowcagr/sensitivity/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens0.nc",
            "-30": PREFIX + f"results/nz_2035_lowfix_lowcagr/sensitivity/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens-30.nc",
            "30": PREFIX + f"results/nz_2035_lowfix_lowcagr/sensitivity/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens30.nc",
            }

In [38]:
tech_colors = PREFIX + "config/tech_colors.yaml"

### Validation

In [39]:
# Compare the network solved using the sensitivity workflow vs the regular workflow

n_regular = pypsa.Network(PREFIX + "results/nz_2035_lowfix_lowcagr/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export.nc")

n_sens0 = pypsa.Network(PREFIX + "results/nz_2035_lowfix_lowcagr/sensitivity/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens0.nc")

WARNING:pypsa.io:Importing network from PyPSA version v0.24.0 while current version is v0.26.2. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline NZ.15_1 -> NZ.17_1', 'H2 pipeline NZ.17_1 -> NZ.1_1',
       'H2 pipeline NZ.1_1 -> NZ.11_1'],
      dtype='object', name='name')
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline NZ.15_1 -> NZ.17_1', 'H2 pipeline NZ.17_1 -> NZ.1_1',
       'H2 pipeline NZ.1_1 -> NZ.11_1'],
      dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline NZ.15_1 -> NZ.17_1', 'H2 pipeline NZ.17_1 -> NZ.1_1',
       'H2 pipeline NZ.1_1 -> NZ.11_1'],
      dtype='object', name='name')
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline NZ.15_1 -> NZ.17_1', 'H2 pipeline NZ.17_1 -> NZ.1_1',
       'H2 pipeline NZ.1_1 -> NZ.11_1'],
      dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens0.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [40]:
n_regular.objective, n_sens0.objective

(7014961300.759552, 7017463284.322601)

In [41]:
get_weighted_hydrogen_price(n_regular)

55.681889879924654

In [42]:
get_weighted_hydrogen_price(n_sens0)

55.704181128947596

In [43]:
(n_regular.statistics().loc["Generator",:]/1e6).round(1)

,Optimal Capacity,Installed Capacity,Capacity Factor,Dispatch,Transmission,Withdrawal,Supply,Curtailment,Capital Expenditure,Operational Expenditure,Revenue,Market Value
Coal,0.0,0.0,0.0,3.8,0.0,0.0,3.8,0.0,176.7,108.5,147.6,0.0
Combined-Cycle Gas,0.0,0.0,0.0,3.5,0.0,0.0,3.5,0.0,183.3,135.6,135.6,0.0
Geothermal,0.0,0.0,0.0,9.8,0.0,0.0,9.8,0.0,377.9,0.1,344.2,0.0
Offshore Wind (AC),0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Offshore Wind (DC),0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Oil,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.7,0.0,0.0,0.0
Onshore Wind,0.0,0.0,0.0,10.4,0.0,0.0,10.4,0.3,327.4,0.3,325.1,0.0
Open-Cycle Gas,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.7,0.0,0.0,0.0
Run of River,0.0,0.0,0.0,2.8,0.0,0.0,2.8,0.0,120.4,0.0,95.8,0.0
Solar,0.0,0.0,0.0,7.1,0.0,0.0,7.1,0.0,198.2,0.1,229.6,0.0
gas,0.0,0.0,0.0,33.6,0.0,0.0,33.6,0.0,0.0,675.5,675.5,0.0
residential rural solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
residential urban decentral solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
services rural solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
services urban decentral solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
urban central solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
(n_sens0.statistics().loc["Generator",:]/1e6).round(1)

,Optimal Capacity,Installed Capacity,Capacity Factor,Dispatch,Transmission,Withdrawal,Supply,Curtailment,Capital Expenditure,Operational Expenditure,Revenue,Market Value
Coal,0.0,0.0,0.0,3.8,0.0,0.0,3.8,0.0,176.7,108.5,147.7,0.0
Combined-Cycle Gas,0.0,0.0,0.0,3.5,0.0,0.0,3.5,0.0,183.3,135.7,135.7,0.0
Geothermal,0.0,0.0,0.0,9.8,0.0,0.0,9.8,0.0,377.9,0.2,344.2,0.0
Offshore Wind (AC),0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Offshore Wind (DC),0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Oil,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.7,0.0,0.0,0.0
Onshore Wind,0.0,0.0,0.0,10.4,0.0,0.0,10.4,0.3,327.4,0.4,325.2,0.0
Open-Cycle Gas,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.7,0.0,0.0,0.0
Run of River,0.0,0.0,0.0,2.8,0.0,0.0,2.8,0.0,120.4,0.1,95.8,0.0
Solar,0.0,0.0,0.0,7.1,0.0,0.0,7.1,0.0,198.2,0.2,229.7,0.0
gas,0.0,0.0,0.0,33.6,0.0,0.0,33.6,0.0,0.0,675.8,675.8,0.0
residential rural solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
residential urban decentral solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
services rural solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
services urban decentral solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
urban central solar thermal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Data preparation

In [45]:
def get_weighted_hydrogen_price(n):

    # Get H2 buses
    buses_h2 = n.buses[n.buses.carrier == "H2"].index

    hydrogen_price = n.buses_t.marginal_price[buses_h2]

    # hydrogen balance for H2 buses: set any positive values (net exports) to zero so only demand remains
    h2_balance = n.statistics.energy_balance(aggregate_time=False, aggregate_bus=False).loc[:,:,"H2",buses_h2]
    hydrogen_demand = h2_balance.clip(upper=0)
    hydrogen_demand = hydrogen_demand.groupby("bus").sum().T

    # Weighted average over location and time
    weighted_hydrogen_price = (hydrogen_price * hydrogen_demand).mean() / hydrogen_demand.mean()
    weighted_hydrogen_price = weighted_hydrogen_price.mean()

    return weighted_hydrogen_price

In [46]:
def get_weighted_electricity_price(n):

    # Get AC buses
    buses_ac = n.buses[n.buses.carrier == "AC"].index

    electricity_price = n.buses_t.marginal_price[buses_ac]

    # electricity balance for AC buses: set any positive values (net exports) to zero so only demand remains
    el_balance = n.statistics.energy_balance(aggregate_time=False, aggregate_bus=False).loc[:,:,"AC",buses_ac]
    electricity_demand = el_balance.clip(upper=0)
    electricity_demand = electricity_demand.groupby("bus").sum().T

    # Weighted average over location and time
    weighted_electricity_price = (electricity_price * electricity_demand).mean() / electricity_demand.mean()
    weighted_electricity_price = weighted_electricity_price.mean()

    return weighted_electricity_price

In [47]:
def get_analysis(show_demand=True):
    """Get dispatch
    """

    objective_all = pd.DataFrame()
    electricity_price_all = pd.DataFrame()
    hydrogen_price_all = pd.DataFrame()

    for sc in scenarios:

        n = pypsa.Network(scenarios[sc])

        objective_all = pd.concat([objective_all, pd.DataFrame([n.objective], index=[sc])], axis=0)
        electricity_price_all = pd.concat([electricity_price_all, pd.DataFrame([get_weighted_electricity_price(n)], index=[sc])], axis=0)
        hydrogen_price_all = pd.concat([hydrogen_price_all, pd.DataFrame([get_weighted_hydrogen_price(n)], index=[sc])], axis=0)


    return objective_all, electricity_price_all, hydrogen_price_all

In [48]:
objective, electricity_price, hydrogen_price = get_analysis(show_demand=False)

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline NZ.15_1 -> NZ.17_1', 'H2 pipeline NZ.17_1 -> NZ.1_1',
       'H2 pipeline NZ.1_1 -> NZ.11_1'],
      dtype='object', name='name')
WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline NZ.15_1 -> NZ.17_1', 'H2 pipeline NZ.17_1 -> NZ.1_1',
       'H2 pipeline NZ.1_1 -> NZ.11_1'],
      dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens0.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/scl38887/Documents/git/pypsa-nz/results/nz_2035_lowfix_lowcagr/sensitivity/postnetworks/elec_s_10_ec_lc3.0_CO2L_3H_2035_0.071_BU_10export_sens-30.nc'